### ISSUE TITLE
Feature Request: Expose `ExtractUrlOptions` Type for Import in Projects

### ISSUE THREAD

**Issue by Albert-Andrei** [Gamote/goturl#1]
Hello,

I am currently utilizing the function `extractUrl` in my project, which leverages the `goturl` package for URL extraction from strings. This function is incredibly useful for parsing and manipulating URLs within our data processing workflows. However, I've encountered a limitation regarding the `ExtractUrlOptions` type, which is utilized for configuring the `extractUrl` function's behavior.

As of now, the `ExtractUrlOptions` type is not explicitly exported or made available for import in consumer projects. This restriction poses a challenge for type safety and code readability, especially in TypeScript projects where leveraging explicit types is a best practice. The ability to import `ExtractUrlOptions` would greatly enhance the developer experience by providing direct access to the type definitions, enabling better integration and utilization of the `extractUrl` function within TypeScript environments.

Therefore, I kindly request the addition of an export statement for the `ExtractUrlOptions` type. This change would allow developers to import the type directly into their projects, thus promoting better type checking and facilitating more robust and maintainable code.

Here is a brief overview of the current implementation that highlights the absence of an export for `ExtractUrlOptions`:

```typescript
type ExtractUrlOptions = {
    getLongestUrl?: boolean;
    tryFixProtocol?: boolean;
    fallbackProtocol?: string;
};
/**
 * This method is going to extract the first url found in the input string
 * using the {@link urlRegexSafe} from the `url-regex-safe` package.
 *
 * @param input
 * @param options
 */
declare const extractUrl: (input: unknown, options?: ExtractUrlOptions) => null | string;

export { extractUrl };


Exposing ExtractUrlOptions would not only facilitate type safety but also encourage the adoption of best practices by enabling developers to leverage the full capabilities of TypeScript's type system.

Thank you for considering this feature request. I believe that making ExtractUrlOptions publicly available would be a valuable enhancement for all users of the goturl package.

**Comment by Gamote** [comment]
@Albert-Andrei The request should be fulfilled by the [v3.6.19](https://github.com/Gamote/goturl/releases/tag/v3.6.19) release.

---

💡 Btw, it is not the case for this library, but if you ever find yourself in a similar situation, instead of manually defining the type you could extract the parameters using `Parameters`. Not ideally but a bit closer to the proper solution (keep the types in sync):
```ts
type ExtractUrlOptions = Parameters<typeof extractUrl>[1];
```
